[phases.setup]
nixPkgs = ["jdk17_headless", "maven"]

[phases.build]
cmds = ["cd backend && mvn clean package -DskipTests"]

[start]
cmd = "java -jar backend/target/backend-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod"
